### Prueba de funcionalidad para el carrito

### ------------------------------------------------------------------------------ ###

### Post - Crear carrito
POST http://localhost:8080/api/carrito HTTP/1.1
content-type:application/json

{
    
}

### ------------------------------------------------------------------------------ ###

### Delete - Eliminar un carrito por su id (carrito inexistente)
DELETE http://localhost:8080/api/carrito/6 HTTP/1.1
content-type:application/json

### Delete - Eliminar un carrito por su id (carrito existente)
DELETE http://localhost:8080/api/carrito/3 HTTP/1.1
content-type:application/json
### ------------------------------------------------------------------------------ ###

### Gets

### Get con id de un carrito con productos
GET http://localhost:8080/api/carrito/1/productos/ HTTP/1.1
content-type:application/json

### Get con id de un carrito sin productos
GET http://localhost:8080/api/carrito/2/productos/ HTTP/1.1
content-type:application/json

### Get con id inexistente
GET http://localhost:8080/api/carrito/100/productos/ HTTP/1.1
content-type:application/json

### Get con id no numérico
GET http://localhost:8080/api/carrito/idtres/productos/ HTTP/1.1
content-type:application/json

### ------------------------------------------------------------------------------ ###


### Put
PUT http://localhost:8080/api/carrito/2 HTTP/1.1
content-type:application/json

{
    "name": "Calculadora",
    "description": "Anda bien",
    "code": 12312414,
    "thumbnail": "https://cdn3.iconfinder.com/data/icons/education-209/64/calculator-math-tool-school-256.png",
    "price": 234.56,
    "stock": 3    
}

