### Prueba de funcionalidad para el carrito

### ------------------------------------------------------------------------------ ###

### Post - Crear carrito
POST http://localhost:8080/api/carrito HTTP/1.1
content-type:application/json

{
    
}

### ------------------------------------------------------------------------------ ###

### Delete - Eliminar un carrito por su id (carrito inexistente)
DELETE http://localhost:8080/api/carrito/10 HTTP/1.1
content-type:application/json

### Delete - Eliminar un carrito por su id
DELETE http://localhost:8080/api/carrito/6 HTTP/1.1
content-type:application/json

### Delete - Eliminar un carrito con id no númerico
DELETE http://localhost:8080/api/carrito/veinte HTTP/1.1
content-type:application/json

### Delete - Eliminar un carrito con id de mongoDB
DELETE http://localhost:8080/api/carrito/637faf31f9dfb804875e3b5e HTTP/1.1
content-type:application/json

### Delete - Eliminar un carrito con id de firebase
DELETE http://localhost:8080/api/carrito/K4uGSoLHBxSW9FVclVRc HTTP/1.1
content-type:application/json



### ------------------------------------------------------------------------------ ###

### Gets

### Get con id de un carrito con productos
GET http://localhost:8080/api/carrito/4/productos/ HTTP/1.1
content-type:application/json

### Get con id de un carrito sin productos
GET http://localhost:8080/api/carrito/3/productos/ HTTP/1.1
content-type:application/json

### Get con id inexistente
GET http://localhost:8080/api/carrito/100/productos/ HTTP/1.1
content-type:application/json

### Get con id no numérico
GET http://localhost:8080/api/carrito/idtres/productos/ HTTP/1.1
content-type:application/json

### Get con id de mongoDB
GET http://localhost:8080/api/carrito/632b8490ef15c2c8e52168fc/productos/ HTTP/1.1
content-type:application/json

### Get con id de firebase
GET http://localhost:8080/api/carrito/RzVlX8beRSymhoKL8a06/productos/ HTTP/1.1
content-type:application/json

### ------------------------------------------------------------------------------ ###


### Post - Agregar producto con id específico a carrito con id determinado
POST http://localhost:8080/api/carrito/6/productos/2 HTTP/1.1
content-type:application/json

{
  "quantity": 5
}

### Post - Agregar producto a carrito con id inexistente
POST http://localhost:8080/api/carrito/100/productos/4 HTTP/1.1
content-type:application/json

{
  "quantity": 5
}

### Post - Agregar producto con id inexistente a carrito
POST http://localhost:8080/api/carrito/2/productos/100 HTTP/1.1
content-type:application/json

{
  "quantity": 5
}

### Post - Agregar producto con id no númerico a carrito
POST http://localhost:8080/api/carrito/2/productos/idcuatro HTTP/1.1
content-type:application/json

{
  "quantity": 5 
}

### Post - Agregar producto a carrito ingresando id no númerico
POST http://localhost:8080/api/carrito/iddiez/productos/2 HTTP/1.1
content-type:application/json

{
  "quantity": 5    
}

### Post - Agregar producto a carrito mediante mongoDB
POST http://localhost:8080/api/carrito/632bb5fe3e4205c46ae012ad/productos/632bbd3352facedf4295b935 HTTP/1.1
content-type:application/json

{
  "quantity": 4 
}

### Post - Agregar producto a carrito mediante firebase
POST http://localhost:8080/api/carrito/WGih19AdZ3fpsmEuenju/productos/uCLIAkRf2teDk7vSG4TT HTTP/1.1
content-type:application/json

{
  "quantity": 4 
}



### ------------------------------------------------------------------------------ ###

### Delete
DELETE http://localhost:8080/api/carrito/6/productos/2 HTTP/1.1
content-type:application/json


### Delete - Intento de borrado de producto que no existe en el carrito
DELETE http://localhost:8080/api/carrito/4/productos/100 HTTP/1.1
content-type:application/json

### Delete - Intento de borrado de un producto de un carrito inexistente
DELETE http://localhost:8080/api/carrito/100/productos/1 HTTP/1.1
content-type:application/json

### Delete - Intento de borrado de un producto de un carrito con id no numerico
DELETE http://localhost:8080/api/carrito/hola/productos/1 HTTP/1.1
content-type:application/json

### Delete - Intento de borrado de un producto de un carrito con id no numerico
DELETE http://localhost:8080/api/carrito/1/productos/hola HTTP/1.1
content-type:application/json

### Delete - Borrado de un producto de un carrito con mongoDB
DELETE http://localhost:8080/api/carrito/632bb5fe3e4205c46ae012ad/productos/6329209a83451dd02583589f HTTP/1.1
content-type:application/json

### Delete - Borrado de un producto de un carrito con firebase
DELETE http://localhost:8080/api/carrito/WGih19AdZ3fpsmEuenju/productos/uCLIAkRf2teDk7vSG4TT HTTP/1.1
content-type:application/json